name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake animation (SVG)
        uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: Aanishnithin07 # YOUR GITHUB USERNAME HERE
          outputs: |
            ./output/github-contribution-grid-snake.svg # Path where the snake SVG will be saved
            # If you want a dark theme alternative, uncomment the line below:
            # ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: main
          build_dir: ./output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
